#!/usr/bin/env python
####################################################################################
# The PenTesters Framework (PTF) - Automatic Penetration Testing Platform Creation
# Written by: David Kennedy (ReL1K)
# Twitter: @TrustedSec, @HackingDave
# Website: https://www.trustedsec.com
####################################################################################

from src.core import *
import sys
import subprocess
import os
import socket

try:
    import httplib
except:
    import http.client as httplib

# create launcher
def create_launcher():
    cwd = os.getcwd()
    filewrite = open("%s/ptf" % BASE_BIN_PATH, "w")
    filewrite.write("#!/bin/sh\ncd %s\nchmod +x ptf\n./ptf $*" % (cwd))
    filewrite.close()
    subprocess.Popen("chmod +x %s/ptf" % BASE_BIN_PATH, shell=True).wait()

# check for an Internet connection
def check_internet():
    try:
        print_status("You can always type ./ptf --no-network-connection to skip the Internet check..")
        print_status("Checking for an Internet connection...")
        rhost = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
        rhost.connect(('google.com', 0))
        rhost.settimeout(2)
        return True

    except Exception:
        return False

def have_internet():
    conn = httplib.HTTPConnection("www.google.com", timeout=5)
    try:
        conn.request("HEAD", "/")
        conn.close()
        return True
    except:
        conn.close()
        return False

def check_if_sudo_needed():
    result = subprocess.Popen("touch %s/ptf" % BASE_INSTALL_PATH, shell=True).wait()
    return result == 1


# some OS doesn't have BASE_BIN_PATH create them if not
if not os.path.isdir(BASE_BIN_PATH): os.makedirs(BASE_BIN_PATH)


if check_if_sudo_needed():
    print("\nThe Pentesters Framework (PTF) - by David Kennedy (ReL1K)")
    print("\nThis needs to be run as root. Please sudo it up! Exiting...")
    exit()

try:

    # Bypass network check with argument
    if not "--no-network-connection" in sys.argv[1:]:
        # check internet connection
        if not have_internet():
            print_warning("Unable to detect Internet connection. Needed for PTF.")
            print_warning("We will now exit PTF. Launch again when you got a connection.")
            print_warning("You can also run ptf with the --no-network-connection argument to bypass the network check.")
            sys.exit()

        # try to update ourself first
        print_status("Trying to update myself first.. Then starting framework.")
        subprocess.Popen("git pull", shell=True).wait()

    # create automatic launcher
    # create_launcher()

    # pull in the core library
    from src.core import *

    # pull in the framework
    import src.framework

    # if we want to skip going into module
    if  "--update-all" in sys.argv[1:]:
        if "-y" in sys.argv[1:]:
            src.framework.handle_prompt("use modules/install_update_all", True)
        else:
            src.framework.handle_prompt("use modules/install_update_all")
    elif "--update-installed" in sys.argv[1:]:
        src.framework.handle_prompt("use modules/update_installed")
    else:
        # or just ask what you want
        src.framework.mainloop()

except KeyboardInterrupt:
    print("\n")
    print_status("Exiting PTF - the easy pentest platform creation framework.")
    exit()
    sys.exit()

except Exception as e:
    print_error("[!] DANGER WILL ROBINSON. DANGER WILL ROBINSON. Error has occured.")
    print_error("[!] It's not possible its due to my coding skillz, it must be you? :-)")
    print_error(("[!] Printing that error. Get that error. You get it: " + str(e)))
